{
    'name': 'Legal LIFF Pages',
    'version': '18.0.1.0.0',
    'category': 'Services/Legal',
    'summary': 'LIFF pages for LINE in-app browser (intake, status, etc.)',
    'author': 'Zemons',
    'depends': ['legal_case', 'line_integration'],
    'data': [
        'security/ir.model.access.csv',
        'data/document_template_data.xml',
        'data/document_cron.xml',
        'data/clause_data.xml',
        'views/document_template_views.xml',
        'views/legal_clause_views.xml',
        'views/liff_templates.xml',
    ],
    'post_init_hook': '_post_init_sync_template_fields',
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
